name: Sync branch to main

on:
  push:
    branches:
      - "**"
  workflow_dispatch:

jobs:
  sync:
    if: github.ref_name != 'main'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0

      - name: Download latest branch as ZIP
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          ZIP_URL="https://github.com/${{ github.repository }}/archive/refs/heads/$BRANCH_NAME.zip"
          curl -L -o "$BRANCH_NAME.zip" "$ZIP_URL"

      - name: Remove old branch folder
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          rm -rf "$BRANCH_NAME"

      - name: Extract new files
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          mkdir "$BRANCH_NAME"
          unzip "$BRANCH_NAME.zip" -d .
          mv "${{ github.event.repository.name }}-$BRANCH_NAME/"* "$BRANCH_NAME/"
          rm -rf "${{ github.event.repository.name }}-$BRANCH_NAME" "$BRANCH_NAME.zip"

      - name: Get latest commit message from the source branch
        id: get_commit_info
        run: |
          BRANCH_NAME=${GITHUB_REF#refs/heads/}
          git fetch origin $BRANCH_NAME
          git log origin/$BRANCH_NAME -1 --pretty=%B > commit_message.txt

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit --author="${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>" -F commit_message.txt || exit 0
          git push origin main
