name: Update Classes

on:
  schedule:
    - cron: "0 */24 * * *"
  workflow_dispatch:
  repository_dispatch:
    types: [update_class]
  push:
    branches:
      - "**"

jobs:
  classUpdate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - id: update-src
        uses: metro420yt/class-update@v1-rc3
        with:
          folder: .
          ext: theme.css
          diff: "https://raw.githubusercontent.com/SyndiShanX/Update-Classes/main/Changes.txt"
      - uses: EndBug/add-and-commit@v9
        if: ${{steps.update-src.outputs.totalChanges > 0 || steps.update-build.outputs.totalChanges > 0}}
        with:
          default_author: github_actions
          message: "chore: update classes"
          fetch: true
